# Generated by Django 5.1.7 on 2025-03-13 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('trainee', '0005_alter_trainee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
    ]
