# Generated by Django 5.1.7 on 2025-03-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0006_trainee_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
